routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->middleware(['guest']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get(
    '/digital-forms/birth-certificate/create/{id}',
    'DigitalFormController@birthCertificate'
);

/* Admin Routes */
Route::group(
    ['prefix' => 'admin',  'middleware' => 'auth'],
    function () {
        Route::get(
            '/admin-profiles/edit-account/{id}',
            'AdministratorController@editAccount'
        )->name('account.edit');

        Route::put(
            '/admin-profiles/update-account/{id}',
            'AdministratorController@updateAccount'
        )->name('account.update');

        Route::get(
            '/admin-profile-list',
            'AdministratorController@adminProfileDatatable'
        )->name('admin-profile-list');

        Route::get(
            '/admin-profiles/delete/{id}',
            'AdministratorController@delete'
        )->name('admin-profiles.delete');

        Route::resource('admin-profiles', 'AdministratorController');
        
        Route::get(
            '/requestor-profile-list',
            'RequestorController@requestorDatatable'
        )->name('requestor-profile-list');

        Route::get(
            '/requestor-profiles/delete/{id}',
            'RequestorController@delete'
        )->name('requestor-profiles.delete');

        Route::resource('requestor-profiles', 'RequestorController');

        Route::get(
            '/access-control-list',
            'AccessControlController@accessControlDatatable'
        )->name('access-control-list');

        Route::get(
            '/access-controls/delete/{id}',
            'AccessControlController@delete'
        )->name('access-controls.delete');

        Route::resource('access-controls', 'AccessControlController');

        Route::get(
            '/department-list',
            'DepartmentController@departmentDatatable'
        )->name('department-list');

        Route::get(
            '/departments/delete/{id}',
            'DepartmentController@delete'
        )->name('departments.delete');

        Route::resource('departments', 'DepartmentController');

        Route::get(
            '/designation-list',
            'DesignationController@designationtDatatable'
        )->name('designation-list');

        Route::get(
            '/designations/delete/{id}',
            'DesignationController@delete'
        )->name('designations.delete');

        Route::get(
            '/form-list',
            'FormController@formDatatable'
        )->name('form-list');

        Route::get(
            '/forms/delete/{id}',
            'FormController@delete'
        )->name('forms.delete');

        Route::resource('forms', 'FormController');

        Route::resource('designations', 'DesignationController');

        Route::get(
            '/request-form-list',
            'RequestFormController@requestFormDatatable'
        )->name('request-form-list');

        Route::get(
            '/request-forms/delete/{id}',
            'RequestFormController@delete'
        )->name('request-forms.delete');

        Route::get(
            '/download-docs/{docId}',
            'RequestFormController@downloadDocs'
        )->name('download-docs');

        Route::resource('request-forms', 'RequestFormController');

        Route::get(
            '/download-docs-activities/{docId}',
            'AdminRequestActivityController@downloadDocs'
        )->name('download-docs-activities');

        Route::get(
            '/admin-request-activities/{requestedId}',
            'AdminRequestActivityController@create'
        )->name('admin-request-activities.create');

        Route::get(
            '/admin-request-activities/{requestedId}/activities/{activityId}',
            'AdminRequestActivityController@show'
        )->name('admin-request-activities.show');

        Route::post(
            '/admin-request-activities/{requestedId}',
            'AdminRequestActivityController@store'
        )->name('admin-request-activities.store');

        Route::get(
            '/emergency-request-list',
            'EmergencyRequestController@emergencyRequestDatatable'
        )->name('emergency-request-list');

        Route::get(
            '/emergency-requests/delete/{id}',
            'EmergencyRequestController@delete'
        )->name('emergency-requests.delete');

        Route::resource('emergency-requests', 'EmergencyRequestController');

        Route::get(
            '/notification-list',
            'NotificationController@notificationDatatable'
        )->name('notification-list');

        Route::get('notifications', 'NotificationController@index')->name('notification.index');
    }
);

Route::get('notification/mark-read', 'NotificationController@readAllNotification')->name('markAsRead');

Route::put('notification/{id}', 'NotificationController@markAsViewNotification')->name('markAsView');

app/Http/Controllers/AccessControlController.php
<?php

namespace App\Http\Controllers;

use App\Module;
use App\ModulePermission;
use App\Restriction;
use App\UserPermission;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

use function App\Common\modulePermission;
use function App\Datatable\action_data;

class AccessControlController extends Controller
{
    private $module;
    /**
     * construct
     */
    public function __construct()
    {
        $this->module = Module::where('module_name', 'access_control')->first();
    }

    /**
     * index
     *
     * @return void
     */
    public function index()
    {
        return view(
            'access-control.index'
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $modules = Module::where('access', '!=', null)->get();
        $restrictions = Restriction::all();

        return view(
            'access-control.create',
            [
                'modules' => $modules,
                'restrictions' => $restrictions
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $userPermission = UserPermission::create($this->payload($request));

        foreach ($request->modules as $key => $module) {
            if ($request->input('access_' . $module) != null) {
                ModulePermission::create([
                    'permission_id' => $userPermission->id,
                    'module_id' => $module,
                    'access' => json_encode($request->input('access_' . $module))
                ]);
            }
        }

        return array(
            "status" => "success",
            'data' => $userPermission,
            'desc' => 'Access Control Successfully Created!'
        );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(int $accessId)
    {
        $userPermission = UserPermission::findOrFail($accessId);

        return view(
            'access-control.show',
            ["accessControl" =>  $userPermission]
        );
    }

    /**
     * edit
     *
     * @param int $accessId
     *
     * @return void
     */
    public function edit(int $accessId)
    {
        $userPermission = UserPermission::findOrFail($accessId);
        $modules = Module::where('access', '!=', null)->get();
        $restrictions = Restriction::all();

        return view(
            'access-control.edit',
            [
                "accessControl" =>  $userPermission,
                'modules' => $modules,
                'restrictions' => $restrictions
            ]
        );
    }

    /**
     * update
     *
     * @param Request $request
     * @param int $accessId
     *
     * @return void
     */
    public function update(Request $request, int $accessId)
    {
        $userPermission = UserPermission::findOrFail($accessId);

        $userPermission->update($this->payload($request));

        $moduleId = array();
        $dataArr = array();
        foreach ($userPermission->modulePermission()->get() as $key => $ids) {
            $moduleId[] = $ids->module_id;
        }

        foreach ($request->modules as $key => $module) {
            if ($request->input('access_' . $module) != null) {
                if (in_array($module, $moduleId)) {
                    $dataArr[] = (int)$module;
                    $userPermission->modulePermission()->where('module_id', $module)->update([
                        'permission_id' => $userPermission->id,
                        'module_id' => $module,
                        'access' => json_encode($request->input('access_' . $module))
                    ]);
                } else {
                    ModulePermission::create([
                        'permission_id' => $userPermission->id,
                        'module_id' => $module,
                        'access' => json_encode($request->input('access_' . $module))
                    ]);
                }
            }
        }
        $result = array_diff($moduleId, $dataArr);

        foreach ($result as $id) {
            $permission = ModulePermission::where('module_id', $id)
                ->where('permission_id', $userPermission->id)->first();
                
            $permission->delete();
        }

        return array(
            "status" => "success",
            'data' => $userPermission,
            'desc' => 'Access Control Successfully Updated!'
        );
    }
    
    /**
     * destroy
     *
     * @param int $permissionId
     *
     * @return void
     */
    public function destroy(int $accessId)
    {
        $permission = UserPermission::findOrFail($accessId);

        $permission->delete();

        return redirect(route('access-controls.index'));
    }

    /**
     * delete
     *
     * @param int $accessId
     *
     * @return void
     */
    public function delete(int $accessId)
    {
        $accessControl = UserPermission::findOrFail($accessId);

        return view(
            'access-control.delete',
            ['accessControl' => $accessControl]
        );
    }

    /**
     * datatables
     *
     * @return void
     */
    public function accessControlDatatable()
    {
        $userPermissions = UserPermission::all();

        $dt = DataTables::of($userPermissions)
        ->addColumn('name', function ($model) {
            return $model->name;
        })
        ->addColumn('description', function ($model) {
            return $model->description;
        })
        ->addColumn('user_type', function ($model) {
            return ucwords($model->user_type);
        })
        ->addColumn('action', function ($model) {
            return action_data(
                route('access-controls.edit', $model->id),
                route('access-controls.delete', $model->id),
                $this->module
            );
        })->make(true);

        return $dt;
    }

    /**
     * Validation Rules for Store and Update
     *
     * @param Request $request
     *
     * @return array
     */
    public function payload(Request $request): array
    {
        return $this->validate(
            $request,
            [
                'name' => 'required',
                'description' => 'nullable',
                'user_type' => 'required'
            ]
        );
    }
}

resources/views/access-control/create.blade.php
@extends('layouts.app')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Access Controls</h1>
<p class="mb-4">User Access Controls for Municipality Officials.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div align='right' style="margin-top: -21px;">
            <a href="{{ route('access-controls.index') }}">
                <button type="button" style="margin-bottom: -44px;" class="btn btn-default">
                <i class="fas fa-chevron-left"></i> Back</button
            ></a>
        </div>
        <h6 class="m-0 font-weight-bold text-primary">Create New Access Control</h6>
    </div>
    
    <div class="card-body">
        <!-- Nested Row within Card Body -->
        <div class="errors"></div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="p-5">
                    <form class="user" method="POST" id ="access-control-create" action="{{ route('access-controls.store') }}">
                        @csrf
                        <div class="form-group">
                            <input type="text" class="form-control form-control"
                                    placeholder="Access Control name" data-validation="required" name="name"
                                    style="border-right: solid 4px #f6c23e">
                        </div>
                        <div class="form-group">
                            <select style="border-left: solid 2.0px #ec0000" 
                                class="form-control" placeholder="User Type"
                                name="user_type" value="" data-validation="required">
                                <option value="admin">Admin</option>
                                <option value="user">User</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="description"></textarea>
                        </div>
                        <div class="col-md-12">
                            <table class="table table-striped table-bordered table-hover text-center table-mediascreen" style="margin-top: 50px">
                                <thead class="thead-dark">
                                    <tr align="center">
                                        <th width="70%" rowspan="2" style="text-align:center" >Modules</th>
                                        <th width="30%" colspan="2" style="text-align:center" >Permissions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($modules as $module)
                                        <tr>
                                            <td>{{ $module->name }}<input type="hidden" name="modules[]" value="{{ $module->id }}"></td>
                                            <td>
                                                <select class="form-control select-picker" name="access_{{$module->id}}[]" multiple>
                                                    @foreach($restrictions as $restriction)
                                                        @php
                                                            $access = array();
                                                            $access = json_decode($module->access);
                                                        @endphp
                                                        @if (in_array($restriction->id, $access))
                                                            <option value="{{ $restriction->id }}">{{ $restriction->name }}</option>
                                                        @endif
                                                    @endforeach
                                                </select>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn btn-success btn-icon-split">
                                <span class="icon text-white-50">
                                    <i class="fas fa-save"></i>
                                </span>
                                <span class="text">Submit</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
    <script>
        $('#access-control-create').register_fields('.errors');

        $('.select-picker').selectpicker();
    </script>
    <!-- Page level custom scripts -->
    <script src="{{ asset('web-design/js/demo/datatables-demo.js') }}"></script>
@endpush
@endsection

resources/views/access-control/delete.blade.php
<form method="POST" id="remove_access_control_form"  class="form-horizontal" action="{{route('access-controls.destroy',$accessControl->id)}}" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="DELETE">
    {{csrf_field()}}
    <h6> Are you sure you want to delete {{$accessControl->name}}?</h6>
    <div class="form-group" style="margin-top: 20px">
        <div class="col-12" align="right">
            <div class="col-12">
                <a href="{{route('access-controls.index')}}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                <button type="submit" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</form>

resources/views/access-control/edit.blade.php
@extends('layouts.app')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Access Controls</h1>
<p class="mb-4">User Access Controls for Municipality Officials.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div align='right' style="margin-top: -21px;">
            <a href="{{ route('access-controls.index') }}">
                <button type="button" style="margin-bottom: -44px;" class="btn btn-default">
                <i class="fas fa-chevron-left"></i> Back</button
            ></a>
        </div>
        <h6 class="m-0 font-weight-bold text-primary">Edit Access Control</h6>
    </div>
    
    <div class="card-body">
        <!-- Nested Row within Card Body -->
        <div class="errors"></div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="p-5">
                    <form class="user" method="POST" id ="access-control-edit" action="{{ route('access-controls.update', $accessControl->id) }}">
                        <input type="hidden" name="_method" value="PUT">
                        @csrf
                        <div class="form-group">
                            <input type="text" class="form-control form-control"
                                    value="{{ $accessControl->name }}"
                                    placeholder="Access Control name" data-validation="required" name="name"
                                    style="border-right: solid 4px #f6c23e">
                        </div>
                        <div class="form-group">
                            <select style="border-right: solid 4px #f6c23e" 
                                class="form-control" placeholder="User Type"
                                name="user_type" value="" data-validation="required">
                                <option value="admin" {{ $accessControl->user_type == 'admin' ? 'selected' : ''}}>Admin</option>
                                <option value="user" {{ $accessControl->user_type == 'user' ? 'selected' : ''}}>User</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="description">{{ $accessControl->description }}</textarea>
                        </div>
                        <div class="col-md-12">
                            <table class="table table-striped table-bordered table-hover text-center table-mediascreen" style="margin-top: 50px">
                                <thead class="thead-dark">
                                    <tr align="center">
                                        <th width="70%" rowspan="2" style="text-align:center" >Modules</th>
                                        <th width="30%" colspan="2" style="text-align:center" >Permissions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($modules as $module)
                                        @php
                                            $getModule = $accessControl->modulePermission()->where('module_id', $module->id)->first();
                                            $userModule = array();
                                            if($getModule) {
                                                $userModule = json_decode($getModule->access);
                                            }
                                        @endphp
                                        <tr>
                                            <td>{{ $module->name }}<input type="hidden" name="modules[]" value="{{ $module->id }}"></td>
                                            <td>
                                                <select class="form-control select-picker" name="access_{{$module->id}}[]" multiple>
                                                    @foreach($restrictions as $restriction)
                                                        @php
                                                            $access = array();
                                                            $access = json_decode($module->access);
                                                        @endphp
                                                        @if (in_array($restriction->id, $access))
                                                            <option 
                                                                value="{{ $restriction->id }}" 
                                                                {{ (in_array($restriction->id, $userModule) ? 'selected' : '' ) }}
                                                            >{{ $restriction->name }}</option>
                                                        @endif
                                                    @endforeach
                                                </select>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn btn-success btn-icon-split">
                                <span class="icon text-white-50">
                                    <i class="fas fa-edit"></i>
                                </span>
                                <span class="text">Update</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
    <script>
        $('#access-control-edit').register_fields('.errors');
        $('.select-picker').selectpicker();
    </script>
    <!-- Page level custom scripts -->
    <script src="{{ asset('web-design/js/demo/datatables-demo.js') }}"></script>
@endpush
@endsection

resources/views/access-control/index.blade.php
@extends('layouts.app')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Access Controls</h1>
<p class="mb-4">User Access Controls for Municipality Officials.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Access Control List</h6>
    </div>
    <div class="card-body">
        <div align='right' style="margin-bottom: 20px;">
            <a href="{{ route('access-controls.create') }}" class="btn btn-primary btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-plus"></i>
                </span>
                <span class="text">New</span>
            </a>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered" id="access-control-table" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th scope="col" width="30%">Access Control Name</th>
                        <th scope="col" width="40%">Description</th>
                        <th scope="col" width="22%">User Type</th>
                        <th scope="col" width="8%">Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@push('scripts')
    <script>
        $(function() {
            $('#access-control-table').DataTable(
                {
                    responsive: true,
                    pagingType: "full_numbers",
                    processing: true,
                    serverSide: true,
                    type: "GET",
                    ajax:"{!! route('access-control-list') !!}",
                    columns:[
                        {data: "name","name":"name","width":"30%",
                            "render": function (data, type, row, meta) {
                                var url = '{{ route("access-controls.show", ":id") }}';
                                url = url.replace(':id', row.id);
                                return "<a href='"+url+"'>"+data+"</a>"; 
                        }},
                        {data: "description","name":"description","width":"40%"},
                        {data: "user_type","name":"user_type","width":"22%"},
                        {data: "action","name":"action",orderable:false,searchable:false,"width":"8%"},
                    ]
                }
            );
        });
    </script>
    <!-- Page level custom scripts -->
    <script src="{{ asset('web-design/js/demo/datatables-demo.js') }}"></script>
@endpush
@endsection

resources/views/access-control/show.blade.php
@extends('layouts.app')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Access Controls</h1>
<p class="mb-4">User Access Controls for Municipality Officials.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div align='right' style="margin-top: -21px;">
            <a href="{{ route('access-controls.index') }}">
                <button type="button" style="margin-bottom: -44px;" class="btn btn-default">
                <i class="fas fa-chevron-left"></i> Back</button
            ></a>
        </div>
        <h6 class="m-0 font-weight-bold text-primary">{{ $accessControl->name }}</h6>
    </div>
    
    <div class="card-body">
        <!-- Nested Row within Card Body -->
        <div class="errors"></div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><b>Access Control Name</b></label><br>
                        <p>&nbsp;{{ $accessControl->name }}</p>
                    </div>
                    <div class="form-group col-md-6"></div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><b>User Type</b></label><br>
                        <p>&nbsp;{{ ucwords($accessControl->user_type) }}</p>
                    </div>
                    <div class="form-group col-md-6"></div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><b>Description</b></label><br>
                        <p>&nbsp;{{ $accessControl->description != null ? $accessControl->description : 'N/A' }}</p>
                    </div>
                    <div class="form-group col-md-6"></div>
                </div>
                <div class="col-md-12">
                    <table class="table table-striped table-bordered table-hover text-center table-mediascreen" style="margin-top: 50px">
                        <thead class="thead-dark">
                            <tr align="center">
                                <th width="50%">Modules</th>
                                <th width="50%">Permission</th>
                            </tr>
                        </thead>
                        <tbody class="report" name="report" id="table_item">
                            @foreach($accessControl->modulePermission as $module)
                                <tr align="left">
                                    <td>{{ $module->module->name }}</td>
                                    <td>{{ App\Common\restrictions($module->access) }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection