routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->middleware(['guest']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get(
    '/digital-forms/birth-certificate/create/{id}',
    'DigitalFormController@birthCertificate'
);

/* Admin Routes */
Route::group(
    ['prefix' => 'admin',  'middleware' => 'auth'],
    function () {
        Route::get(
            '/admin-profiles/edit-account/{id}',
            'AdministratorController@editAccount'
        )->name('account.edit');

        Route::put(
            '/admin-profiles/update-account/{id}',
            'AdministratorController@updateAccount'
        )->name('account.update');

        Route::get(
            '/admin-profile-list',
            'AdministratorController@adminProfileDatatable'
        )->name('admin-profile-list');

        Route::get(
            '/admin-profiles/delete/{id}',
            'AdministratorController@delete'
        )->name('admin-profiles.delete');

        Route::resource('admin-profiles', 'AdministratorController');
        
        Route::get(
            '/requestor-profile-list',
            'RequestorController@requestorDatatable'
        )->name('requestor-profile-list');

        Route::get(
            '/requestor-profiles/delete/{id}',
            'RequestorController@delete'
        )->name('requestor-profiles.delete');

        Route::resource('requestor-profiles', 'RequestorController');

        Route::get(
            '/access-control-list',
            'AccessControlController@accessControlDatatable'
        )->name('access-control-list');

        Route::get(
            '/access-controls/delete/{id}',
            'AccessControlController@delete'
        )->name('access-controls.delete');

        Route::resource('access-controls', 'AccessControlController');

        Route::get(
            '/department-list',
            'DepartmentController@departmentDatatable'
        )->name('department-list');

        Route::get(
            '/departments/delete/{id}',
            'DepartmentController@delete'
        )->name('departments.delete');

        Route::resource('departments', 'DepartmentController');

        Route::get(
            '/designation-list',
            'DesignationController@designationtDatatable'
        )->name('designation-list');

        Route::get(
            '/designations/delete/{id}',
            'DesignationController@delete'
        )->name('designations.delete');

        Route::get(
            '/form-list',
            'FormController@formDatatable'
        )->name('form-list');

        Route::get(
            '/forms/delete/{id}',
            'FormController@delete'
        )->name('forms.delete');

        Route::resource('forms', 'FormController');

        Route::resource('designations', 'DesignationController');

        Route::get(
            '/request-form-list',
            'RequestFormController@requestFormDatatable'
        )->name('request-form-list');

        Route::get(
            '/request-forms/delete/{id}',
            'RequestFormController@delete'
        )->name('request-forms.delete');

        Route::get(
            '/download-docs/{docId}',
            'RequestFormController@downloadDocs'
        )->name('download-docs');

        Route::resource('request-forms', 'RequestFormController');

        Route::get(
            '/download-docs-activities/{docId}',
            'AdminRequestActivityController@downloadDocs'
        )->name('download-docs-activities');

        Route::get(
            '/admin-request-activities/{requestedId}',
            'AdminRequestActivityController@create'
        )->name('admin-request-activities.create');

        Route::get(
            '/admin-request-activities/{requestedId}/activities/{activityId}',
            'AdminRequestActivityController@show'
        )->name('admin-request-activities.show');

        Route::post(
            '/admin-request-activities/{requestedId}',
            'AdminRequestActivityController@store'
        )->name('admin-request-activities.store');

        Route::get(
            '/emergency-request-list',
            'EmergencyRequestController@emergencyRequestDatatable'
        )->name('emergency-request-list');

        Route::get(
            '/emergency-requests/delete/{id}',
            'EmergencyRequestController@delete'
        )->name('emergency-requests.delete');

        Route::resource('emergency-requests', 'EmergencyRequestController');

        Route::get(
            '/notification-list',
            'NotificationController@notificationDatatable'
        )->name('notification-list');

        Route::get('notifications', 'NotificationController@index')->name('notification.index');
    }
);

Route::get('notification/mark-read', 'NotificationController@readAllNotification')->name('markAsRead');

Route::put('notification/{id}', 'NotificationController@markAsViewNotification')->name('markAsView');

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;

class Department extends Model
{
    use SoftDeletes;

    protected $table = 'departments';

    protected $fillable = [
        'name',
        'description'
    ];

    /**
     * designation relationship
     *
     * @return HasMany
     */
    public function designations(): HasMany
    {
        return $this->hasMany(Designation::class, 'department_id');
    }

    /**
     * hotline relationship
     *
     * @return HasOne
     */
    public function hotline(): HasOne
    {
        return $this->hasOne(DepartmentHotline::class, 'department_id');
    }
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Department;
use App\DepartmentHotline;
use App\Module;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

use function App\Common\modulePermission;
use function App\Datatable\action_data;

class DepartmentController extends Controller
{
    private $module;
    /**
     * construct
     */
    public function __construct()
    {
        $this->module = Module::where('module_name', 'department')->first();
    }

    /**
     * index
     *
     * @return void
     */
    public function index()
    {
        return view(
            'department.index'
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view(
            'department.create'
        );
    }

    /**
     * store
     *
     * @param Request $request
     *
     * @return void
     */
    public function store(Request $request)
    {
        $department = Department::create($this->payload($request));

        if ($request->has('emergency')) {
            $request->merge(['department_id' => $department->id]);
            $hotlines = DepartmentHotline::create($this->payloadHotline($request));
        }

        return array(
            "status" => "success",
            'data' => $department,
            'desc' => 'Department' . $department->name . ' Successfully Created!'
        );
    }

    /**
     * show
     *
     * @param int $deptId
     *
     * @return void
     */
    public function show(int $deptId)
    {
        $department = Department::findOrFail($deptId);

        return view(
            'department.show',
            ['department' => $department]
        );
    }

    /**
     * edit
     *
     * @param int $deptId
     *
     * @return void
     */
    public function edit(int $deptId)
    {
        $department = Department::findOrFail($deptId);

        return view(
            'department.edit',
            ['department' => $department]
        );
    }

    /**
     * update
     *
     * @param Request $request
     * @param int $deptId
     *
     * @return void
     */
    public function update(Request $request, int $deptId)
    {
        $department = Department::findOrFail($deptId);

        $department->update($this->payload($request));

        if ($request->has('emergency')) {
            $request->merge(['department_id' => $department->id]);
            $department->hotline()->update($this->payloadHotline($request));
        }

        return array(
            "status" => "success",
            'data' => $department,
            'desc' => 'Department Record Successfully Updated!'
        );
    }

    /**
     * delete
     *
     * @param int $deptId
     *
     * @return void
     */
    public function delete(int $deptId)
    {
        $department = Department::findOrFail($deptId);

        return view(
            'department.delete',
            ['department' => $department]
        );
    }

    /**
     * destroy
     *
     * @param int $deptId
     *
     * @return void
     */
    public function destroy(int $deptId)
    {
        $department = Department::findOrFail($deptId);

        $department->delete();

        return redirect(route('departments.index'));
    }

    /**
     * datatables
     *
     * @return void
     */
    public function departmentDatatable()
    {
        $department = Department::all();

        $dt = DataTables::of($department)
        ->addColumn('id', function ($model) {
            return $model->id;
        })
        ->addColumn('name', function ($model) {
            return $model->name;
        })
        ->addColumn('description', function ($model) {
            return $model->description != null ? $model->description : 'N/A';
        })
        ->addColumn('action', function ($model) {
            return action_data(
                route('departments.edit', $model->id),
                route('departments.delete', $model->id),
                $this->module
            );
        })->make(true);

        return $dt;
    }

    /**
     * Validation Rules for Store and Update
     *
     * @param Request $request
     *
     * @return array
     */
    public function payload(Request $request): array
    {
        return $this->validate(
            $request,
            [
                'name' => 'required',
                'description' => 'nullable'
            ]
        );
    }

    /**
     * Validation Rules for Store and Update
     *
     * @param Request $request
     *
     * @return array
     */
    public function payloadHotline(Request $request): array
    {
        return $this->validate(
            $request,
            [
                'department_id' => 'required',
                'mobile_number' => 'nullable',
                'telephone' => 'required'
            ]
        );
    }
}

resources/views/department/create.blade.php
@extends('layouts.app')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Department</h1>
<p class="mb-4">Department on the Municipality Record.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div align='right' style="margin-top: -21px;">
            <a href="{{ route('departments.index') }}">
                <button type="button" style="margin-bottom: -44px;" class="btn btn-default">
                <i class="fas fa-chevron-left"></i> Back</button
            ></a>
        </div>
        <h6 class="m-0 font-weight-bold text-primary">Create New Department</h6>
    </div>
    
    <div class="card-body">
        <!-- Nested Row within Card Body -->
        <div class="errors"></div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="p-5">
                    <form class="user" method="POST" id ="department-create" action="{{ route('departments.store') }}">
                        @csrf
                        <div class="form-group">
                            <input type="text" class="form-control form-control" id="exampleFirstName"
                                    placeholder="Department Name" data-validation="required" name="name"
                                    style="border-right: solid 4px #f6c23e">
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="description" placeholder="Add Department Description..."></textarea>
                        </div>
                        <div class="form-group">
                            <p>Add Emergency Response?</p>
                            <div class="form-check">
                                <input class="form-check-input checkbox_check" type="checkbox" name="emergency" id="exampleRadios1" value="1">
                                <label class="form-check-label" for="exampleRadios1">
                                    Yes
                                </label>
                            </div>
                        </div>
                        <div id="hotlines">
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn btn-success btn-icon-split">
                                <span class="icon text-white-50">
                                    <i class="fas fa-save"></i>
                                </span>
                                <span class="text">Submit</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
    <script>
        $('#department-create').register_fields('.errors');

        $('#exampleRadios1').click( function () {
            if ($('input.checkbox_check').is(':checked')) {
                //$('#hotlines').show();
                $('#hotlines').append(''+
                            '<div class="form-group">'+
                                '<input type="text" class="form-control form-control" '+
                                    ' id="exampleFirstName" placeholder="Mobile Number Hotline" '+
                                    ' name="mobile_number" '+
                                    ' style="border-right: solid 4px #f6c23e">'+
                            '</div>'+
                            '<div class="form-group">'+
                                '<input type="text" class="form-control form-control" id="exampleFirstName"'+
                                        'placeholder="Telephone Hotline" data-validation="required" name="telephone"'+
                                        'style="border-right: solid 4px #f6c23e">'+
                            '</div>');
            } else {
                //$('#hotlines').hide();
                $('#hotlines > div').remove();
            }
        });
    </script>
    <!-- Page level custom scripts -->
    <script src="{{ asset('web-design/js/demo/datatables-demo.js') }}"></script>
@endpush
@endsection

resources/views/department/delete.blade.php
<form method="POST" id="remove_bhw_form"  class="form-horizontal" action="{{route('departments.destroy',$department->id)}}" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="DELETE">
    {{csrf_field()}}
    <h6> Are you sure you want to delete {{$department->name}}?</h6>
    <div class="form-group" style="margin-top: 20px">
        <div class="col-12" align="right">
            <div class="col-12">
                <a href="{{route('departments.index')}}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                <button type="submit" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</form>

resources/views/department/edit.blade.php
@extends('layouts.app')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Department</h1>
<p class="mb-4">Department on the Municipality Record.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div align='right' style="margin-top: -21px;">
            <a href="{{ route('departments.index') }}">
                <button type="button" style="margin-bottom: -44px;" class="btn btn-default">
                <i class="fas fa-chevron-left"></i> Back</button
            ></a>
        </div>
        <h6 class="m-0 font-weight-bold text-primary">Edit Department</h6>
    </div>
    
    <div class="card-body">
        <!-- Nested Row within Card Body -->
        <div class="errors"></div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="p-5">
                    <form class="user" method="POST" id ="department-create" action="{{ route('departments.update', $department->id) }}">
                        <input type="hidden" name="_method" value="PUT">
                        @csrf
                        <div class="form-group">
                            <input type="text" class="form-control form-control" id="exampleFirstName"
                                    placeholder="Department Name" data-validation="required" name="name"
                                    style="border-right: solid 4px #f6c23e" value="{{ $department->name }}">
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="description" 
                                placeholder="Add Department Description...">{{ $department->description }}</textarea>
                        </div>
                        <div class="form-group">
                            <p>Add Emergency Response?</p>
                            <div class="form-check">
                                <input class="form-check-input checkbox_check" type="checkbox" name="emergency" id="exampleRadios1" value="1" {{ $department->hotline ? 'checked' : '' }}>
                                <label class="form-check-label" for="exampleRadios1" >
                                    Yes
                                </label>
                            </div>
                        </div>
                        <div id="hotlines">
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn btn-success btn-icon-split">
                                <span class="icon text-white-50">
                                    <i class="fas fa-edit"></i>
                                </span>
                                <span class="text">Update</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
    <script>
        $('#department-create').register_fields('.errors');
        $(document).ready(function() {
            if ($('input.checkbox_check').is(':checked')) {
                append();
            } else {
                $('#hotlines > div').remove();
            }
        });

        $('#exampleRadios1').click( function () {
            if ($('input.checkbox_check').is(':checked')) {
                append();
            } else {
                $('#hotlines > div').remove();
            }
        });

        function append()
        {
            $('#hotlines').append(''+
                            '<div class="form-group">'+
                                '<input type="text" class="form-control form-control" '+
                                    ' id="exampleFirstName" placeholder="Mobile Number Hotline" '+
                                    ' name="mobile_number" '+
                                    ' value="{{ $department->hotline ? $department->hotline->mobile_number : ''}}"'+
                                    ' style="border-right: solid 4px #f6c23e">'+
                            '</div>'+
                            '<div class="form-group">'+
                                '<input type="text" class="form-control form-control" id="exampleFirstName"'+
                                        ' value="{{$department->hotline ? $department->hotline->telephone : '' }}"'+
                                        'placeholder="Telephone Hotline" data-validation="required" name="telephone"'+
                                        'style="border-right: solid 4px #f6c23e">'+
                            '</div>');
        }
    </script>
    <!-- Page level custom scripts -->
    <script src="{{ asset('web-design/js/demo/datatables-demo.js') }}"></script>
@endpush
@endsection

resources/views/department/index.blade.php
@extends('layouts.app')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Department</h1>
<p class="mb-4">Department on the Municipality Record.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Department List</h6>
    </div>
    <div class="card-body">
        <div align='right' style="margin-bottom: 20px;">
            <a href="{{ route('departments.create') }}" class="btn btn-primary btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-plus"></i>
                </span>
                <span class="text">New</span>
            </a>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered" id="department-table" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@push('scripts')
    <script>
        $(function() {
            $('#department-table').DataTable(
                {
                    responsive: true,
                    pagingType: "full_numbers",
                    processing: true,
                    serverSide: true,
                    type: "GET",
                    ajax:"{!! route('department-list') !!}",
                    columns:[
                        {data: "name","name":"name","width":"50%",
                            "render": function (data, type, row, meta) {
                                var url = '{{ route("departments.show", ":id") }}';
                                url = url.replace(':id', row.id);
                                return "<a href='"+url+"'>"+data+"</a>"; 
                        }},
                        {data: "description","name":"description","width":"40%"},
                        {data: "action","name":"action",orderable:false,searchable:false,"width":"8%"},
                    ]
                }
            );
        });
    </script>
    <!-- Page level custom scripts -->
    <script src="{{ asset('web-design/js/demo/datatables-demo.js') }}"></script>
@endpush
@endsection

resources/views/department/show.blade.php
@extends('layouts.app')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Department</h1>
<p class="mb-4">Department on the Municipality Record.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div align='right' style="margin-top: -21px;">
            <a href="{{ route('departments.index') }}">
                <button type="button" style="margin-bottom: -44px;" class="btn btn-default">
                <i class="fas fa-chevron-left"></i> Back</button
            ></a>
        </div>
        <h6 class="m-0 font-weight-bold text-primary">{{ $department->name }}</h6>
    </div>
    
    <div class="card-body">
        <!-- Nested Row within Card Body -->
        <div class="errors"></div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><b>Name</b></label><br>
                        <p>&nbsp;{{ $department->name }}</p>
                    </div>
                    <div class="form-group col-md-6"></div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><b>Description</b></label><br>
                        <p>&nbsp;{{ $department->description != null ? $department->description : 'N/A' }}</p>
                    </div>
                    <div class="form-group col-md-6"></div>
                </div>
                @if ($department->hotline)
                <h5>Hotlines:</h5>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><b>Mobile Number</b></label><br>
                        <p>&nbsp;{{ $department->hotline->mobile_number }}</p>
                    </div>
                    <div class="form-group col-md-6"></div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><b>Telephone</b></label><br>
                        <p>&nbsp;{{ $department->hotline->telephone }}</p>
                    </div>
                    <div class="form-group col-md-6"></div>
                </div>
                @endIf
            </div>
        </div>
    </div>
</div>
@endsection