routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->middleware(['guest']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get(
    '/digital-forms/birth-certificate/create/{id}',
    'DigitalFormController@birthCertificate'
);

/* Admin Routes */
Route::group(
    ['prefix' => 'admin',  'middleware' => 'auth'],
    function () {
        Route::get(
            '/admin-profiles/edit-account/{id}',
            'AdministratorController@editAccount'
        )->name('account.edit');

        Route::put(
            '/admin-profiles/update-account/{id}',
            'AdministratorController@updateAccount'
        )->name('account.update');

        Route::get(
            '/admin-profile-list',
            'AdministratorController@adminProfileDatatable'
        )->name('admin-profile-list');

        Route::get(
            '/admin-profiles/delete/{id}',
            'AdministratorController@delete'
        )->name('admin-profiles.delete');

        Route::resource('admin-profiles', 'AdministratorController');
        
        Route::get(
            '/requestor-profile-list',
            'RequestorController@requestorDatatable'
        )->name('requestor-profile-list');

        Route::get(
            '/requestor-profiles/delete/{id}',
            'RequestorController@delete'
        )->name('requestor-profiles.delete');

        Route::resource('requestor-profiles', 'RequestorController');

        Route::get(
            '/access-control-list',
            'AccessControlController@accessControlDatatable'
        )->name('access-control-list');

        Route::get(
            '/access-controls/delete/{id}',
            'AccessControlController@delete'
        )->name('access-controls.delete');

        Route::resource('access-controls', 'AccessControlController');

        Route::get(
            '/department-list',
            'DepartmentController@departmentDatatable'
        )->name('department-list');

        Route::get(
            '/departments/delete/{id}',
            'DepartmentController@delete'
        )->name('departments.delete');

        Route::resource('departments', 'DepartmentController');

        Route::get(
            '/designation-list',
            'DesignationController@designationtDatatable'
        )->name('designation-list');

        Route::get(
            '/designations/delete/{id}',
            'DesignationController@delete'
        )->name('designations.delete');

        Route::get(
            '/form-list',
            'FormController@formDatatable'
        )->name('form-list');

        Route::get(
            '/forms/delete/{id}',
            'FormController@delete'
        )->name('forms.delete');

        Route::resource('forms', 'FormController');

        Route::resource('designations', 'DesignationController');

        Route::get(
            '/request-form-list',
            'RequestFormController@requestFormDatatable'
        )->name('request-form-list');

        Route::get(
            '/request-forms/delete/{id}',
            'RequestFormController@delete'
        )->name('request-forms.delete');

        Route::get(
            '/download-docs/{docId}',
            'RequestFormController@downloadDocs'
        )->name('download-docs');

        Route::resource('request-forms', 'RequestFormController');

        Route::get(
            '/download-docs-activities/{docId}',
            'AdminRequestActivityController@downloadDocs'
        )->name('download-docs-activities');

        Route::get(
            '/admin-request-activities/{requestedId}',
            'AdminRequestActivityController@create'
        )->name('admin-request-activities.create');

        Route::get(
            '/admin-request-activities/{requestedId}/activities/{activityId}',
            'AdminRequestActivityController@show'
        )->name('admin-request-activities.show');

        Route::post(
            '/admin-request-activities/{requestedId}',
            'AdminRequestActivityController@store'
        )->name('admin-request-activities.store');

        Route::get(
            '/emergency-request-list',
            'EmergencyRequestController@emergencyRequestDatatable'
        )->name('emergency-request-list');

        Route::get(
            '/emergency-requests/delete/{id}',
            'EmergencyRequestController@delete'
        )->name('emergency-requests.delete');

        Route::resource('emergency-requests', 'EmergencyRequestController');

        Route::get(
            '/notification-list',
            'NotificationController@notificationDatatable'
        )->name('notification-list');

        Route::get('notifications', 'NotificationController@index')->name('notification.index');
    }
);

Route::get('notification/mark-read', 'NotificationController@readAllNotification')->name('markAsRead');

Route::put('notification/{id}', 'NotificationController@markAsViewNotification')->name('markAsView');

app/Http/Controllers/AdministratorController.php
<?php

namespace App\Http\Controllers;

use App\AdminProfile;
use App\Designation;
use App\Module;
use App\User;
use App\UserAccess;
use App\UserPermission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Yajra\DataTables\DataTables;

use function App\Common\modulePermission;
use function App\Datatable\action_data;

class AdministratorController extends Controller
{
    private $module;
    /**
     * construct
     */
    public function __construct()
    {
        $this->module = Module::where('module_name', 'admin')->first();
    }

    /**
     * index
     *
     * @return void
     */
    public function index()
    {
        return view(
            'administrator.index'
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = UserPermission::all();

        $designations = Designation::all();
        
        return view(
            'administrator.create',
            [
                'permissions' => $permissions,
                'designations' => $designations
            ]
        );
    }

    /**
     * store
     *
     * @param Request $request
     *
     * @return void
     */
    public function store(Request $request)
    {

        $userPayload = $this->payloadAccount($request);

        $adminProfile = AdminProfile::create($this->payload($request));
        
        $user = User::create([
            'name' => $userPayload['name'],
            'email' => $userPayload['email'],
            'password' => Hash::make($userPayload['password']),
            'user_type' => 'App\AdminProfile',
            'user_id' => $adminProfile->id
        ]);

        $access = UserAccess::create([
            'user_id' => $user->id,
            'permission_id' => $request->input('permission_id')
        ]);
        
        return array(
            "status" => "success",
            'data' => $user,
            'desc' => 'Admin Account Successfully Created!'
        );
    }

    /**
     * show
     *
     * @param string $adminId
     *
     * @return void
     */
    public function show(string $adminId)
    {
        $adminProfile = AdminProfile::findOrFail($adminId);
        $user_access = UserAccess::where('user_id', $adminProfile->user->id)->first();
        return view(
            'administrator.show',
            [
                "adminProfile" =>  $adminProfile,
                "userAccess" => $user_access
            ]
        );
    }

    /**
     * edit
     *
     * @param int $adminId
     *
     * @return void
     */
    public function edit(int $adminId)
    {
        $adminProfile = AdminProfile::findOrFail($adminId);

        $permissions = UserPermission::all();

        $designations = Designation::all();

        return view(
            'administrator.edit',
            [
                'adminProfile' => $adminProfile,
                'permissions' => $permissions,
                'designations' => $designations
            ]
        );
    }

    /**
     * update
     *
     * @param Request $request
     * @param int $adminId
     *
     * @return void
     */
    public function update(
        Request $request,
        int $adminId
    ) {
        $adminProfile = AdminProfile::findOrFail($adminId);

        $adminProfile->update($this->payload($request));

        return array(
            "status" => "success",
            'data' => $adminProfile,
            'desc' => 'Admin Account Successfully Updated!'
        );
    }

    /**
     * delete
     *
     * @param int $adminId
     *
     * @return void
     */
    public function delete(string $adminId)
    {
        $adminProfile = AdminProfile::findOrFail($adminId);

        return view(
            'administrator.delete',
            ['adminProfile' => $adminProfile]
        );
    }

    /**
     * destroy
     *
     * @param int $adminId
     *
     * @return void
     */
    public function destroy(int $adminId)
    {
        $adminProfile = AdminProfile::findOrFail($adminId);

        $user = User::findOrFail($adminProfile->user->id);

        $user->delete();

        $adminProfile->delete();

        return redirect(route('admin-profiles.index'));
    }

    /**
     * Validation Rules for Store and Update
     *
     * @param Request $request
     *
     * @return array
     */
    public function payload(Request $request): array
    {
        return $this->validate(
            $request,
            [
                'first_name' => 'required',
                'middle_name' => 'nullable',
                'last_name' => 'required',
                'designation_id' => 'required',
                'birth_date' => 'required',
                'contact_no' => 'nullable'
            ]
        );
    }

    /**
     * Validation Rules for Store and Update for account
     *
     * @param Request $request
     *
     * @return array
     */
    public function payloadAccount(Request $request): array
    {
        return $this->validate(
            $request,
            [
                'name' => [
                    'required',
                    'string',
                    'max:255'
                ],
                'email' => [
                    'required',
                    'string',
                    'email',
                    'max:255'
                ],
                'password' => [
                    'required',
                    'string',
                    'min:8',
                    'confirmed'
                ],
                'user_type' => 'nullable',
                'user_id' => 'nullable'
            ]
        );
    }

    /**
     * edit account
     *
     * @param int $adminId
     *
     * @return void
     */
    public function editAccount(int $adminId)
    {
        $permissions = UserPermission::all();
        $adminProfile = AdminProfile::findOrFail($adminId);
        return view(
            'administrator.edit-account',
            [
                'permissions' => $permissions,
                'adminProfile' => $adminProfile
            ]
        );
    }

    /**
     * change password
     *
     * @param Request $request
     *
     * @return void
     */
    public function updateAccount(
        Request $request,
        int $userId
    ) {
        $user = User::findOrFail($userId);

        $requestData = $this->payloadAccount($request);
        $requestData['password'] = Hash::make($request->password);

        $user->update($requestData);

        return array(
            "status" => "success",
            'data' => $user,
            'desc' => 'Account Successfully Updated!'
        );
    }
    /**
     * datatables
     *
     * @return void
     */
    public function adminProfileDatatable()
    {
        $department = AdminProfile::all();

        $dt = DataTables::of($department)
        ->addColumn('id', function ($model) {
            return $model->id;
        })
        ->addColumn('name', function ($model) {
            return $model->last_name . ', ' . $model->first_name;
        })
        ->addColumn('position', function ($model) {
            return $model->designation->name;
        })
        ->addColumn('department', function ($model) {
            return $model->designation->department->name;
        })
        ->addColumn('contact_no', function ($model) {
            return $model->contact_no;
        })
        ->addColumn('birth_date', function ($model) {
            return date('F d, Y', strtotime($model->birth_date));
        })
        ->addColumn('action', function ($model) {
            return action_data(
                route('admin-profiles.edit', $model->id),
                route('admin-profiles.delete', $model->id),
                $this->module
            );
        })->make(true);

        return $dt;
    }
}

resources/views/administrator/create.blade.php
@extends('layouts.app')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Administrator</h1>
<p class="mb-4">Administrator are the one who access Web Portal for SMART CALACA.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div align='right' style="margin-top: -21px;">
            <a href="{{ route('admin-profiles.index') }}">
                <button type="button" style="margin-bottom: -44px;" class="btn btn-default">
                <i class="fas fa-chevron-left"></i> Back</button
            ></a>
        </div>
        <h6 class="m-0 font-weight-bold text-primary">Create New Admin</h6>
    </div>
    
    <div class="card-body">
        <!-- Nested Row within Card Body -->
        <div class="errors"></div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="p-5">
                    <div class="text-center">
                        <h2 class="h4 text-gray-900 mb-4">Basic Information</h2>
                    </div>
                    <form class="user" method="POST" id ="admin-create" action="{{ route('admin-profiles.store') }}">
                        @csrf
                        <div class="form-group">
                            <input type="text" class="form-control form-control" id="exampleFirstName"
                                    placeholder="First Name" data-validation="required"
                                    name="first_name"
                                    style="border-right: solid 4px #f6c23e">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control form-control" id="exampleFirstName"
                                    name="middle_name"
                                    placeholder="Middle Name">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control form-control" id="exampleFirstName"
                                    placeholder="Last Name" data-validation="required"
                                    name="last_name"
                                    style="border-right: solid 4px #f6c23e">
                        </div>
                        <div class="form-group">
                            <select type="text" class="form-control form-control" 
                                style="border-right: solid 4px #f6c23e" name="designation_id" data-validation="required">
                                <option value="">Select Designation</option>
                                @foreach ($designations as $designation)
                                    <option value="{{ $designation->id }}">{{ $designation->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control form-control" id="exampleFirstName"
                                    placeholder="Contact No." data-validation="required"
                                    name="contact_no"
                                    style="border-right: solid 4px #f6c23e">
                        </div>
                        <div class="form-group">
                            <input type="date" class="form-control form-control" id="exampleFirstName"
                                    placeholder="Birth Date" data-validation="required"
                                    name="birth_date"
                                    style="border-right: solid 4px #f6c23e">
                        </div>
                        <div class="text-center">
                            <h2 class="h4 text-gray-900 mb-4">Account Information</h2>
                        </div>
                        <hr>
                        <div class="form-group">
                            <input type="text" class="form-control form-control" id="exampleInputEmail"
                                placeholder="User Name" data-validation="required"
                                name="name"
                                style="border-right: solid 4px #f6c23e">
                        </div>
                        <div class="form-group">
                            <select type="text" class="form-control form-control" data-validation="required" 
                            style="border-right: solid 4px #f6c23e" name="permission_id">
                                <option value="">Select Access Control</option>
                                @foreach ($permissions as $permission)
                                    <option value="{{ $permission->id }}">{{ $permission->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control form-control" id="exampleInputEmail"
                                placeholder="Email Address" data-validation="required"
                                name="email"
                                style="border-right: solid 4px #f6c23e">
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <input type="password" class="form-control form-control"
                                    id="exampleInputPassword" data-validation="required"
                                    name="password"
                                    placeholder="Password" style="border-right: solid 4px #f6c23e">
                            </div>
                            <div class="col-sm-6">
                                <input type="password" class="form-control"
                                    id="password-confirm" data-validation="required"
                                    name="password_confirmation"
                                    placeholder="Repeat Password" style="border-right: solid 4px #f6c23e">
                            </div>
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn btn-success btn-icon-split">
                                <span class="icon text-white-50">
                                    <i class="fas fa-save"></i>
                                </span>
                                <span class="text">Submit</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
    <script>
        $('#admin-create').register_fields('.errors');
    </script>
    <!-- Page level custom scripts -->
    <script src="{{ asset('web-design/js/demo/datatables-demo.js') }}"></script>
@endpush
@endsection

resources/views/administrator/delete.blade.php
<form method="POST" id="remove_admin_form"  class="form-horizontal" action="{{route('admin-profiles.destroy',$adminProfile->id)}}" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="DELETE">
    {{csrf_field()}}
    <h6> Are you sure you want to delete {{$adminProfile->first_name}}?</h6>
    <div class="form-group" style="margin-top: 20px">
        <div class="col-12" align="right">
            <div class="col-12">
                <a href="{{route('admin-profiles.index')}}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                <button type="submit" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</form>

resources/views/administrator/edit.blade.php
@extends('layouts.app')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Administrator</h1>
<p class="mb-4">Administrator are the one who access Web Portal for SMART CALACA.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div align='right' style="margin-top: -21px;">
            <a href="{{ route('admin-profiles.index') }}">
                <button type="button" style="margin-bottom: -44px;" class="btn btn-default">
                <i class="fas fa-chevron-left"></i> Back</button
            ></a>
        </div>
        <h6 class="m-0 font-weight-bold text-primary">Edit Administrator Profile</h6>
    </div>
    
    <div class="card-body">
        <!-- Nested Row within Card Body -->
        <div class="errors"></div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="p-5">
                    <div class="text-center">
                        <h2 class="h4 text-gray-900 mb-4">Basic Information</h2>
                    </div>
                    <form class="user" method="POST" id ="admin-edit" action="{{ route('admin-profiles.update', $adminProfile->id) }}">
                        <input type="hidden" name="_method" value="PUT">
                        @csrf
                        <div class="form-group">
                            <input type="text" class="form-control form-control" id="exampleFirstName"
                                    placeholder="First Name" data-validation="required"
                                    name="first_name" value="{{ $adminProfile->first_name }}"
                                    style="border-right: solid 4px #f6c23e">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control form-control" id="exampleFirstName"
                                    name="middle_name" value="{{ $adminProfile->middle_name }}"
                                    placeholder="Middle Name">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control form-control" id="exampleFirstName"
                                    placeholder="Last Name" data-validation="required"
                                    name="last_name" value="{{ $adminProfile->last_name }}"
                                    style="border-right: solid 4px #f6c23e">
                        </div>
                        <div class="form-group">
                            <select type="text" class="form-control form-control" 
                                style="border-right: solid 4px #f6c23e" name="designation_id" data-validation="required">
                                <option value="">Select Designation</option>
                                @foreach ($designations as $designation)
                                    <option value="{{ $designation->id }}" 
                                        {{($designation->id == $adminProfile->designation_id ? 'selected': '' )}}>
                                        {{ $designation->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control form-control" id="exampleFirstName"
                                    placeholder="Contact No." data-validation="required"
                                    name="contact_no" value="{{ $adminProfile->contact_no }}"
                                    style="border-right: solid 4px #f6c23e">
                        </div>
                        <div class="form-group">
                            <input type="date" class="form-control form-control" id="exampleFirstName"
                                    placeholder="Birth Date" data-validation="required"
                                    name="birth_date" value="{{ $adminProfile->birth_date }}"
                                    style="border-right: solid 4px #f6c23e">
                        </div>
                        <div class="text-center">
                            <h2 class="h4 text-gray-900 mb-4">Account Information</h2>
                        </div>
                        <hr>
                        <a href="{{ route('account.edit', $adminProfile->id) }}"><button type="button" class="btn btn-secondary"><i class="fas fa-edit"></i> Edit Account</button></a>
                        <div class="text-right">
                            <button type="submit" class="btn btn-success btn-icon-split">
                                <span class="icon text-white-50">
                                    <i class="fas fa-edit"></i>
                                </span>
                                <span class="text">Update</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
    <script>
        $('#admin-edit').register_fields('.errors');
    </script>
@endpush
@endsection

resources/views/administrator/index.blade.php
@extends('layouts.app')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Administrator</h1>
<p class="mb-4">Administrator are the one who access Web Portal for SMART CALACA.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Administrator List</h6>
    </div>
    <div class="card-body">
        <div align='right' style="margin-bottom: 20px;">
            <a href="{{ route('admin-profiles.create') }}" class="btn btn-primary btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-plus"></i>
                </span>
                <span class="text">New</span>
            </a>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered" id="admin-table" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Position</th>
                        <th>Department</th>
                        <th>Contact No.</th>
                        <th>Birth Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@push('scripts')
<script>
        $(function() {
            $('#admin-table').DataTable(
                {
                    responsive: true,
                    pagingType: "full_numbers",
                    processing: true,
                    serverSide: true,
                    type: "GET",
                    ajax:"{!! route('admin-profile-list') !!}",
                    columns:[
                        {data: "name","name":"name","width":"22%",
                            "render": function (data, type, row, meta) {
                                var url = '{{ route("admin-profiles.show", ":id") }}';
                                url = url.replace(':id', row.id);
                                return "<a href='"+url+"'>"+data+"</a>"; 
                        }},
                        {data: "position","name":"position","width":"20%"},
                        {data: "department","name":"department","width":"20%"},
                        {data: "contact_no","name":"contact_no","width":"15%"},
                        {data: "birth_date","name":"birth_date","width":"15%"},
                        {data: "action","name":"action",orderable:false,searchable:false,"width":"8%"},
                    ]
                }
            );
        });
    </script>
    <!-- Page level custom scripts -->
    <script src="{{ asset('web-design/js/demo/datatables-demo.js') }}"></script>
@endpush
@endsection