routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->middleware(['guest']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get(
    '/digital-forms/birth-certificate/create/{id}',
    'DigitalFormController@birthCertificate'
);

/* Admin Routes */
Route::group(
    ['prefix' => 'admin',  'middleware' => 'auth'],
    function () {
        Route::get(
            '/admin-profiles/edit-account/{id}',
            'AdministratorController@editAccount'
        )->name('account.edit');

        Route::put(
            '/admin-profiles/update-account/{id}',
            'AdministratorController@updateAccount'
        )->name('account.update');

        Route::get(
            '/admin-profile-list',
            'AdministratorController@adminProfileDatatable'
        )->name('admin-profile-list');

        Route::get(
            '/admin-profiles/delete/{id}',
            'AdministratorController@delete'
        )->name('admin-profiles.delete');

        Route::resource('admin-profiles', 'AdministratorController');
        
        Route::get(
            '/requestor-profile-list',
            'RequestorController@requestorDatatable'
        )->name('requestor-profile-list');

        Route::get(
            '/requestor-profiles/delete/{id}',
            'RequestorController@delete'
        )->name('requestor-profiles.delete');

        Route::resource('requestor-profiles', 'RequestorController');

        Route::get(
            '/access-control-list',
            'AccessControlController@accessControlDatatable'
        )->name('access-control-list');

        Route::get(
            '/access-controls/delete/{id}',
            'AccessControlController@delete'
        )->name('access-controls.delete');

        Route::resource('access-controls', 'AccessControlController');

        Route::get(
            '/department-list',
            'DepartmentController@departmentDatatable'
        )->name('department-list');

        Route::get(
            '/departments/delete/{id}',
            'DepartmentController@delete'
        )->name('departments.delete');

        Route::resource('departments', 'DepartmentController');

        Route::get(
            '/designation-list',
            'DesignationController@designationtDatatable'
        )->name('designation-list');

        Route::get(
            '/designations/delete/{id}',
            'DesignationController@delete'
        )->name('designations.delete');

        Route::get(
            '/form-list',
            'FormController@formDatatable'
        )->name('form-list');

        Route::get(
            '/forms/delete/{id}',
            'FormController@delete'
        )->name('forms.delete');

        Route::resource('forms', 'FormController');

        Route::resource('designations', 'DesignationController');

        Route::get(
            '/request-form-list',
            'RequestFormController@requestFormDatatable'
        )->name('request-form-list');

        Route::get(
            '/request-forms/delete/{id}',
            'RequestFormController@delete'
        )->name('request-forms.delete');

        Route::get(
            '/download-docs/{docId}',
            'RequestFormController@downloadDocs'
        )->name('download-docs');

        Route::resource('request-forms', 'RequestFormController');

        Route::get(
            '/download-docs-activities/{docId}',
            'AdminRequestActivityController@downloadDocs'
        )->name('download-docs-activities');

        Route::get(
            '/admin-request-activities/{requestedId}',
            'AdminRequestActivityController@create'
        )->name('admin-request-activities.create');

        Route::get(
            '/admin-request-activities/{requestedId}/activities/{activityId}',
            'AdminRequestActivityController@show'
        )->name('admin-request-activities.show');

        Route::post(
            '/admin-request-activities/{requestedId}',
            'AdminRequestActivityController@store'
        )->name('admin-request-activities.store');

        Route::get(
            '/emergency-request-list',
            'EmergencyRequestController@emergencyRequestDatatable'
        )->name('emergency-request-list');

        Route::get(
            '/emergency-requests/delete/{id}',
            'EmergencyRequestController@delete'
        )->name('emergency-requests.delete');

        Route::resource('emergency-requests', 'EmergencyRequestController');

        Route::get(
            '/notification-list',
            'NotificationController@notificationDatatable'
        )->name('notification-list');

        Route::get('notifications', 'NotificationController@index')->name('notification.index');
    }
);

Route::get('notification/mark-read', 'NotificationController@readAllNotification')->name('markAsRead');

Route::put('notification/{id}', 'NotificationController@markAsViewNotification')->name('markAsView');

app/EmergencyRequest.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class EmergencyRequest extends Model
{
    use SoftDeletes;

    protected $table = 'emergency_requests';

    protected $fillable = [
        'user_id',
        'department_id',
        'area_incident',
        'type_incident',
        'remarks'
    ];

    /**
     * user relationship
     *
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id')->withTrashed();
    }

    /**
     * department relationship
     *
     * @return BelongsTo
     */
    public function department(): BelongsTo
    {
        return $this->belongsTo(Department::class, 'department_id');
    }
    
    /**
     * morphmany logs
     *
     * @return void
     */
    public function getLogs(): MorphMany
    {
        return $this->morphMany(Log::class, "reference");
    }
}

app/Http/Controllers/Api/EmergencyRequestController.php
<?php

namespace App\Http\Controllers\Api;

use App\DepartmentHotline;
use App\EmergencyRequest;
use App\Http\Controllers\Controller;
use App\Http\Resources\DepartmentHotline as DepartmentHotlineResource;
use App\Http\Resources\EmergencyRequest as EmergencyRequestResource;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Http\Resources\Json\ResourceCollection;

use function App\Log\log_created;

class EmergencyRequestController extends Controller
{
    /**
     * index
     *
     * @param int $userId
     *
     * @return ResourceCollection
     */
    public function index(int $userId): ResourceCollection
    {
        $emergency = EmergencyRequest::where('user_id', $userId)->get();

        return EmergencyRequestResource::collection($emergency);
    }

    /**
     * store
     *
     * @param Request $request
     * @param int $userId
     *
     * @return JsonResource
     */
    public function store(
        Request $request,
        int $userId
    ): JsonResource {
        $request->merge(['user_id' => $userId]);

        $emergency = EmergencyRequest::create($this->payload($request));

        log_created($emergency);

        return new EmergencyRequestResource($emergency);
    }

    /**
     * show
     *
     * @param int $userId
     * @param int $requestId
     *
     * @return JsonResource
     */
    public function show(int $userId, int $requestId): JsonResource
    {
        $emergency = EmergencyRequest::where('user_id', $userId)
            ->where('id', $requestId)->first();

        return new EmergencyRequestResource($emergency);
    }

    /**
     * hotlines
     *
     * @return ResourceCollection
     */
    public function hotlines(): ResourceCollection
    {
        $hotlines = DepartmentHotline::all();

        return DepartmentHotlineResource::collection($hotlines);
    }

    /**
     * hotlines
     *
     * @return ResourceCollection
     */
    public function showHotline(int $hotlineId): JsonResource
    {
        $hotline = DepartmentHotline::findOrFail($hotlineId);

        return new DepartmentHotlineResource($hotline);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * payload for Update and Create Emergency Request
     *
     * @param Request $request
     *
     * @return array
     */
    public function payload(Request $request): array
    {
        return $this->validate(
            $request,
            [
                'user_id' => 'required',
                'department_id' => 'required',
                'area_incident' => 'required',
                'type_incident' => 'required',
                'remarks' => 'required'
            ]
        );
    }
}

app/Http/Controllers/EmergencyRequestController.php
<?php

namespace App\Http\Controllers;

use App\EmergencyRequest;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use App\Module;

use function App\Common\modulePermission;
use function App\Datatable\action_data;

class EmergencyRequestController extends Controller
{
    private $module;
    /**
     * construct
     */
    public function __construct()
    {
        $this->module = Module::where('module_name', 'emergency_request')->first();
    }

    /**
     * index
     *
     * @return void
     */
    public function index()
    {
        return view(
            'emergency-request.index'
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(int $requestId)
    {
        $emergency = EmergencyRequest::findOrFail($requestId);

        return view(
            'emergency-request.show',
            ['emergency' => $emergency]
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * delete
     *
     * @param int $requestId
     *
     * @return void
     */
    public function delete(int $requestId)
    {
        $emergency = EmergencyRequest::findOrFail($requestId);

        return view(
            'emergency-request.delete',
            ['emergency' => $emergency]
        );
    }

    /**
     * destroy
     *
     * @param int $requestId
     *
     * @return void
     */
    public function destroy(int $requestId)
    {
        $emergency = EmergencyRequest::findOrFail($requestId);

        $emergency->delete();

        return redirect(route('emergency-requests.index'));
    }

    /**
     * datatables
     *
     * @return void
     */
    public function emergencyRequestDatatable()
    {
        $request = EmergencyRequest::all();

        $dt = DataTables::of($request)
        ->addColumn('id', function ($model) {
            return $model->id;
        })
        ->addColumn('date', function ($model) {
            return $model->created_at;
        })
        ->addColumn('department', function ($model) {
            return $model->department->name;
        })
        ->addColumn('name', function ($model) {
            return $model->user->name;
        })
        ->addColumn('address', function ($model) {
            return $model->user->user->address ? $model->user->user->address : 'N/A';
        })
        ->addColumn('contact_number', function ($model) {
            return $model->user->user->contact_no;
        })
        ->addColumn('area_incident', function ($model) {
            return $model->area_incident;
        })
        ->addColumn('action', function ($model) {
            return action_data(
                null,
                route('emergency-requests.delete', $model->id),
                $this->module
            );
        })->make(true);

        return $dt;
    }
}

resources/views/emergency-request/delete.blade.php
<form method="POST" id="remove_bhw_form"  class="form-horizontal" action="{{route('emergency-requests.destroy',$emergency->id)}}" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="DELETE">
    {{csrf_field()}}
    <h6> Are you sure you want to delete Emergency Request by {{$emergency->user->name}}?</h6>
    <div class="form-group" style="margin-top: 20px">
        <div class="col-12" align="right">
            <div class="col-12">
                <a href="{{route('departments.index')}}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                <button type="submit" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</form>

resources/views/emergency-request/index.blade.php
@extends('layouts.app')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Emergency Request</h1>
<p class="mb-4">Citizen Emergency Request List.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Emergency Request List</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="emergency-request-table" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Department</th>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Contact Number</th>
                        <th>Area of Incident</th>
                        <th>Action</th>

                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@push('scripts')
    <script>
        $(function() {
            $('#emergency-request-table').DataTable(
                {
                    order: [0, 'desc'],
                    responsive: true,
                    pagingType: "full_numbers",
                    processing: true,
                    serverSide: true,
                    type: "GET",
                    ajax:"{!! route('emergency-request-list') !!}",
                    columns:[
                        {data: "date","name":"date","width":"15%"},
                        {data: "department","name":"department","width":"19%",
                            "render": function (data, type, row, meta) {
                                var url = '{{ route("emergency-requests.show", ":id") }}';
                                url = url.replace(':id', row.id);
                                return "<a href='"+url+"'>"+data+"</a>"; 
                        }},
                        {data: "name","name":"name","width":"18%"},
                        {data: "address","name":"address","width":"15%"},
                        {data: "contact_number","name":"contact_number","width":"15%"},
                        {data: "area_incident","name":"area_incident","width":"15%"},
                        {data: "action","name":"action",orderable:false,searchable:false,"width":"8%"},
                    ]
                }
            );
        });
    </script>
    <!-- Page level custom scripts -->
    <script src="{{ asset('web-design/js/demo/datatables-demo.js') }}"></script>
@endpush
@endsection

resources/views/emergency-request/show.blade.php
@extends('layouts.app')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Emergency Request</h1>
<p class="mb-4">Citizen Emergency Request List.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div align='right' style="margin-top: -21px;">
            <a href="{{ route('emergency-requests.index') }}">
                <button type="button" style="margin-bottom: -44px;" class="btn btn-default">
                <i class="fas fa-chevron-left"></i> Back</button
            ></a>
        </div>
        <h6 class="m-0 font-weight-bold text-primary">{{ $emergency->department->name }}</h6>
    </div>
    
    <div class="card-body">
        <!-- Nested Row within Card Body -->
        <div class="errors"></div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><b>Request Department</b></label><br>
                        <p>&nbsp;{{ $emergency->department->name }}</p>
                    </div>
                    <div class="form-group col-md-6"></div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><b>Requestor</b></label><br>
                        <p>&nbsp;{{ $emergency->user->name }}</p>
                    </div>
                    <div class="form-group col-md-6"></div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><b>Area of Incident</b></label><br>
                        <p>&nbsp;{{ $emergency->area_incident }}</p>
                    </div>
                    <div class="form-group col-md-6"></div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><b>Type of Incident</b></label><br>
                        <p>&nbsp;{{ $emergency->type_incident }}</p>
                    </div>
                    <div class="form-group col-md-6"></div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><b>Remarks</b></label><br>
                        <p>&nbsp;{{ $emergency->remarks ? $emergency->remarks : 'N/A' }}</p>
                    </div>
                    <div class="form-group col-md-6"></div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection